function  [plot1]=createfigure_graph(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 19-Jan-2020 00:41:31

% Create figure
figure('InvertHardcopy','off','Color',[1 1 1],...
    'OuterPosition',[31 -5 1280 1000]);

% Create axes
axes1 = axes('Position',[0.03671875 0.11 0.9265625 0.87568281938326]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName','Pin-SVM','Color',[1 0 0]);
set(plot1(2),'DisplayName','Unified Pin-SVM','Color',[0 0 0]);

% Create xlabel
xlabel('\tau');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-1 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[55 85]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',18,'YAxisLocation','origin');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.0364583370353412 0.843612334801762 0.236979162964659 0.143538913362714],...
    'FontSize',20);

